name: Release and Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      KEYSTORE_PATH: ${{ github.workspace }}/app/keystore.jks
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Decode Keystore File
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > ${{ github.workspace }}/app/keystore.jks
        # 确保输出路径与 env.KEYSTORE_PATH 和 build.gradle.kts 中的路径一致

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Library AAR and Demo APK
        run: ./gradlew assembleRelease :app:assembleRelease

      - name: Upload AAR and APK to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            appbar/build/outputs/aar/appbar-release.aar
            app/build/outputs/apk/release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}