name: Release and Publish

on:
  push:
    tags:
      - 'v*' # 推送v开头的tag时触发

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Library AAR and Demo APK
        run: ./gradlew assembleRelease :app:assembleRelease

      - name: Upload AAR and APK to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
           - appbar/build/outputs/aar/appbar-release.aar,
           - app/release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}